### PR TITLE
Fixes ios 16 Xcode 14 build

### PR DESCRIPTION
**Pull request by PJayRushton**

### CODE REVIEW

**Comment by youjinp** [comment]
Are classes not allowed in structs in Xcode 14? What compilation error did you get?

**Comment by PJayRushton** [comment]
Screen Shot 2022-06-17 at 1 29 38 PM

**Comment by youjinp** [comment]
I see. What if we just rename `Coordinator` into `ContactPickerCoordinator`?

**Comment by TheApApp** [comment]
WIll this be merged?

**Comment by kudit** [comment]
Still figuring out GitHub, but I think I submitted the fix to this that @youjinp suggested as a separate pull request.

**Comment by youjinp** [comment]
Fixed in #34

**Pull request closed without merging**
